<div class="demka-news-block-wrapper">
    <div class="demka-news-view-wrapper">
        <img class="demka-news-view-image" src="<?php echo $newsItem->getImage(); ?>"/>
        <div class="demka-news-view-title">
            <h1><?php echo $newsItem->getTitle(); ?></h1>
        </div>
        <div class="demka-news-view-content">
            <div class="content"><?php echo $newsItem->getContent(); ?></div>
        </div>
    </div>
</div>