<?php
/* @var $this Demka_Alert_Block_Email_Stock */
?>
<?php if (!empty($products)): ?>
    <p><?php echo $this->__('You are receiving this notification because you subscribed to receive alerts when the following products are back in stock:') ?></p>
    <table>
        <?php foreach ($products as $product): ?>
            <tr>
                <td>
                    <a href="<?php echo $product->getProductUrl() ?>"
                       title="<?php echo $this->escapeHtml($product->getName()) ?>">
                        <img
                            src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(75,75) ?>"
                            border="0" align="left" height="75" width="75"
                            alt="<?php echo $this->escapeHtml($product->getName()) ?>"
                        />
                    </a>
                </td>
                <td>
                    <p>
                        <a href="<?php echo $product->getProductUrl() ?>"><strong><?php echo $this->escapeHtml($product->getName()) ?></strong></a>
                    </p>
                    <?php $shortDescription = $this->getFilteredProductShortDescription($product) ?>
                    <?php if ($shortDescription): ?>
                        <p><small><?php echo $shortDescription ?></small></p>
                    <?php endif; ?>
                    <p><?php if ($product->getPrice() != $product->getFinalPrice()): ?>
                            <?php echo $this->__('Regular Price:') ?>
                            <strong
                                    style="text-decoration:line-through;"><?php echo Mage::helper('core')->currency($product->getPrice()) ?>
                            </strong>
                            <br/>
                            <strong>
                                <?php echo $this->__('Special price:') ?>
                                <span
                                        style="color:#FF0000;"><?php echo Mage::helper('core')->currency($product->getFinalPrice()) ?>
                                </span>
                            </strong>
                        <?php else: ?>
                            <strong><?php echo $this->__('Price:') ?></strong> <?php echo Mage::helper('core')->currency($product->getPrice()) ?>
                        <?php endif; ?></p>
                    <p>
                        <small><a href="<?php echo $this->getProductUnsubscribeUrl($product->getId(), $customer_email) ?>"><?php echo $this->__('Click here not to receive alerts for this product') ?></a></small>
                    </p>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <p>
        <a href="<?php echo $this->getUnsubscribeUrl($customer_email) ?>"><?php echo $this->__('Unsubscribe from all stock alerts') ?></a>
    </p>
<?php endif; ?>
